name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AZURE_CONTAINER_REGISTRY: ospkrepo.azurecr.io
  IMAGE: ospkrepo.azurecr.io/ospk-web-app

jobs:
  build-and-deploy:
    name: Build and Deploy NodeJS Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.PWD }}" | docker login ${{ env.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.UNAME }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker buildx build --platform linux/amd64 -t ${{ env.IMAGE }}:${{ github.sha }} .  

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE }}:${{ github.sha }}
